defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-26-alpha

version: 2
jobs:
  "Make Dependencies":
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Init Gradle
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  "Run Tests":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  "Build App":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Download Keystore
          command: bash ./ci_scripts/download-keystore.sh
      - run:
          name: Build
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/outputs/apk/
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  "Run Static Code Analysis":
    <<: *defaults
    steps:
      - run:
          name: Static Code Analysis
          command: ./gradlew check
  "Deploy Release":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy APK.
          command: |
              bash ./ci_scripts/deploy-hockey.sh
              bash ./ci_scripts/deploy-fabric.sh
workflows:
  version: 2
  build:
    jobs:
      - "Make Dependencies"
      - "Run Tests":
          requires:
            - "Make Dependencies"
      - "Build App":
          requires:
            - "Make Dependencies"
            - "Run Tests"
      - "Run Static Code Analysis":
          requires:
            - "Make Dependencies"
            - "Build App"
      - "Deploy Release":
          requires:
            - "Make Dependencies"
            - "Build App"
            - "Run Tests"
            - "Run Static Code Analysis"
          filters:
            branches:
              only: master