defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-26-alpha

version: 2
jobs:
  "Make Dependencies":
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Init Gradle
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  "Run Unit Tests":
    <<: *defaults
    steps:
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  "Run CheckStyle":
    <<: *defaults
    steps:
      - run:
          name: Run CkeckStyle
          command: ./gradlew checkstyle
  "Run FindBugs":
    <<: *defaults
    steps:
      - run:
          name: Run FindBugs
          command: ./gradlew findbugs
  "Run PMD":
    <<: *defaults
    steps:
      - run:
          name: Run PMD
          command: ./gradlew pmd
  "Run Lint":
    <<: *defaults
    steps:
      - run:
          name: Run Lint
          command: ./gradlew lint test
  "Build App":
    <<: *defaults
    steps:
      - run:
          name: Build
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks
  deploy:
    <<: *defaults
    steps:
      - deploy:
          name: Deploy Fabrics
          command: ./gradlew crashlyticsUploadDistributionRelease
      - deploy:
          name: Deploy HockeyApp
          command: |
              curl \
              -F "status=2" \
              -F "notify=0" \
              -F "ipa=@app/build/outputs/apk/release/app-release.apk" \
              -H "X-HockeyAppToken: $HOCKEY_APP_TOKEN" \
              https://rink.hockeyapp.net/api/2/apps/$HOCKEY_APP_ID/app_versions/upload
workflows:
  version: 2
  build:
    jobs:
      - "Make Dependencies"
      - "Build App":
          requires:
            - "Make Dependencies"
      - deploy:
          requires:
            - "Make Dependencies"
            - "Build App"